# YOLOv11 Drone Detection Dataset Configuration

# Dataset root path (update this to your dataset location)
path: /content/drone_dataset

# Train/val/test splits
train: train/images
val: valid/images
test: test/images

# Number of classes
nc: 1

# Class names
names:
  0: drone


